[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "18"
  ESLINT_NO_DEV_ERRORS = "true"
  DISABLE_ESLINT_PLUGIN = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
