[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/build"
  environment = { ESLINT_NO_DEV_ERRORS = "true", DISABLE_ESLINT_PLUGIN = "true" }

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
